// <auto-generated />
using System;
using Hephaestus.Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240212194717_M000")]
    partial class M000
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hephaestus.Architect.Models.Active", b =>
                {
                    b.Property<bool>("Id")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name_en")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name_es")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name_pt")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Active", (string)null);

                    b.HasData(
                        new
                        {
                            Id = true,
                            Name = "Yes",
                            Name_en = "Yes",
                            Name_es = "Sí",
                            Name_pt = "Sim"
                        },
                        new
                        {
                            Id = false,
                            Name = "No",
                            Name_en = "No",
                            Name_es = "No",
                            Name_pt = "Não"
                        });
                });

            modelBuilder.Entity("Hephaestus.Architect.Models.Hidden", b =>
                {
                    b.Property<bool>("Id")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name_en")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name_es")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Name_pt")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.HasKey("Id");

                    b.ToTable("Hidden", (string)null);

                    b.HasData(
                        new
                        {
                            Id = true,
                            Name = "Yes",
                            Name_en = "Yes",
                            Name_es = "Sí",
                            Name_pt = "Sim"
                        },
                        new
                        {
                            Id = false,
                            Name = "No",
                            Name_en = "No",
                            Name_es = "No",
                            Name_pt = "Não"
                        });
                });

            modelBuilder.Entity("Hephaestus.Architect.Models.Language", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name_en")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name_es")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name_pt")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Key");

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "pt",
                            Name = "Portuguese",
                            Name_en = "Portuguese (BR)",
                            Name_es = "Portugués (BR)",
                            Name_pt = "Português (BR)"
                        },
                        new
                        {
                            Key = "en",
                            Name = "English",
                            Name_en = "English (US)",
                            Name_es = "Inglés (EUA)",
                            Name_pt = "Inglês (EUA)"
                        },
                        new
                        {
                            Key = "es",
                            Name = "Spanish",
                            Name_en = "Spanish (SP)",
                            Name_es = "Español (ES)",
                            Name_pt = "Espanhol (ES)"
                        });
                });

            modelBuilder.Entity("Hephaestus.Architect.Models.Preferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Theme")
                        .HasColumnType("varchar(5)");

                    b.Property<int>("User")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Language");

                    b.HasIndex("Theme");

                    b.HasIndex("User")
                        .IsUnique();

                    b.ToTable("Preferences", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "pt",
                            Theme = "auto",
                            User = 1
                        },
                        new
                        {
                            Id = 2,
                            Language = "pt",
                            Theme = "auto",
                            User = 2
                        });
                });

            modelBuilder.Entity("Hephaestus.Architect.Models.Theme", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name_en")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name_es")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name_pt")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Key");

                    b.ToTable("Themes", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "auto",
                            Name = "Automatic",
                            Name_en = "Automatic",
                            Name_es = "Automático",
                            Name_pt = "Automático"
                        },
                        new
                        {
                            Key = "light",
                            Name = "Light Theme",
                            Name_en = "Light Theme",
                            Name_es = "Tema Claro",
                            Name_pt = "Tema Claro"
                        },
                        new
                        {
                            Key = "dark",
                            Name = "Dark Theme",
                            Name_en = "Dark Theme",
                            Name_es = "Tema Oscuro",
                            Name_pt = "Tema Escuro"
                        });
                });

            modelBuilder.Entity("Hephaestus.Architect.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Country")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("Hidden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Office")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("varchar(32)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Title")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("Email");

                    b.HasIndex("Guid");

                    b.HasIndex("Hidden");

                    b.HasIndex("Role");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Email = "system@siw.ind.br",
                            Guid = "00000000-0000-0000-0000-000000000000",
                            Hidden = true,
                            Name = "Sistema",
                            Photo = "images/users/unknown.jpg",
                            Role = "System.Admin"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Email = "autobot@siw.ind.br",
                            Guid = "8c4e35a5-2f64-4c28-8644-672f037272c5",
                            Hidden = true,
                            Name = "Autobot",
                            Photo = "images/users/unknown.jpg",
                            Role = "System.Admin"
                        });
                });

            modelBuilder.Entity("Hephaestus.Architect.Models.UserRole", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name_en")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name_es")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name_pt")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Key");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Key = "System.Admin",
                            Name = "System Admin",
                            Name_en = "Administrator",
                            Name_es = "Administrador",
                            Name_pt = "Administrador"
                        },
                        new
                        {
                            Key = "System.Member",
                            Name = "SystemM ember",
                            Name_en = "Moderator",
                            Name_es = "Moderador",
                            Name_pt = "Moderador"
                        },
                        new
                        {
                            Key = "System.User",
                            Name = "System User",
                            Name_en = "System User",
                            Name_es = "Usuario Estándar",
                            Name_pt = "Usuário Padrão"
                        },
                        new
                        {
                            Key = "Engineering.Admin",
                            Name = "Engineering Admin",
                            Name_en = "Engineering (Manager)",
                            Name_es = "Ingeniería (Gerente)",
                            Name_pt = "Engenharia (Gestão)"
                        },
                        new
                        {
                            Key = "Engineering.Member",
                            Name = "Engineering Member",
                            Name_en = "Engineering (Member)",
                            Name_es = "Ingeniería (Miembro)",
                            Name_pt = "Engenharia (Membro)"
                        },
                        new
                        {
                            Key = "Engineering.User",
                            Name = "Engineering User",
                            Name_en = "Engineering (User)",
                            Name_es = "Ingeniería (Usuario)",
                            Name_pt = "Engenharia (Usuário)"
                        },
                        new
                        {
                            Key = "Fiscal.Admin",
                            Name = "Fiscal Admin",
                            Name_en = "Fiscal (Manager)",
                            Name_es = "Fiscal (Gerente)",
                            Name_pt = "Fiscal (Gestão)"
                        },
                        new
                        {
                            Key = "Fiscal.Member",
                            Name = "Fiscal Member",
                            Name_en = "Fiscal (Member)",
                            Name_es = "Fiscal (Miembro)",
                            Name_pt = "Fiscal (Membro)"
                        },
                        new
                        {
                            Key = "Fiscal.User",
                            Name = "Fiscal User",
                            Name_en = "Fiscal (User)",
                            Name_es = "Fiscal (Usuario)",
                            Name_pt = "Fiscal (Usuário)"
                        },
                        new
                        {
                            Key = "Logistics.Admin",
                            Name = "Logistics Admin",
                            Name_en = "Logistics (Manager)",
                            Name_es = "Logística (Gerente)",
                            Name_pt = "Logística (Gestão)"
                        },
                        new
                        {
                            Key = "Logistics.Member",
                            Name = "Logistics Member",
                            Name_en = "Logistics (Member)",
                            Name_es = "Logística (Miembro)",
                            Name_pt = "Logística (Membro)"
                        },
                        new
                        {
                            Key = "Logistics.User",
                            Name = "Logistics User",
                            Name_en = "Logistics (User)",
                            Name_es = "Logística (Usuario)",
                            Name_pt = "Logística (Usuário)"
                        },
                        new
                        {
                            Key = "Maintenance.Admin",
                            Name = "Maintenance Admin",
                            Name_en = "Maintenance (Manager)",
                            Name_es = "Mantenimiento (Gerente)",
                            Name_pt = "Manutenção (Gestão)"
                        },
                        new
                        {
                            Key = "Maintenance.Member",
                            Name = "Maintenance Member",
                            Name_en = "Maintenance (Member)",
                            Name_es = "Mantenimiento (Miembro)",
                            Name_pt = "Manutenção (Membro)"
                        },
                        new
                        {
                            Key = "Maintenance.User",
                            Name = "Maintenance User",
                            Name_en = "Maintenance (User)",
                            Name_es = "Mantenimiento (Usuario)",
                            Name_pt = "Manutenção (Usuário)"
                        },
                        new
                        {
                            Key = "Planning.Admin",
                            Name = "Planning Admin",
                            Name_en = "Planning (Manager)",
                            Name_es = "Planificación (Gerente)",
                            Name_pt = "Planejamento (Gestão)"
                        },
                        new
                        {
                            Key = "Planning.Member",
                            Name = "Planning Member",
                            Name_en = "Planning (Member)",
                            Name_es = "Planificación (Miembro)",
                            Name_pt = "Planejamento (Membro)"
                        },
                        new
                        {
                            Key = "Planning.User",
                            Name = "Planning User",
                            Name_en = "Planning (User)",
                            Name_es = "Planificación (Usuario)",
                            Name_pt = "Planejamento (Usuário)"
                        },
                        new
                        {
                            Key = "Production.Admin",
                            Name = "Production Admin",
                            Name_en = "Production (Manager)",
                            Name_es = "Producción (Gerente)",
                            Name_pt = "Produção (Gestão)"
                        },
                        new
                        {
                            Key = "Production.Member",
                            Name = "Production Member",
                            Name_en = "Production (Member)",
                            Name_es = "Producción (Miembro)",
                            Name_pt = "Produção (Membro)"
                        },
                        new
                        {
                            Key = "Production.User",
                            Name = "Production User",
                            Name_en = "Production (User)",
                            Name_es = "Producción (Usuario)",
                            Name_pt = "Produção (Usuário)"
                        },
                        new
                        {
                            Key = "Quality.Admin",
                            Name = "Quality Admin",
                            Name_en = "Quality (Manager)",
                            Name_es = "Calidad (Gerente)",
                            Name_pt = "Qualidade (Gestão)"
                        },
                        new
                        {
                            Key = "Quality.Member",
                            Name = "Quality Member",
                            Name_en = "Quality (Member)",
                            Name_es = "Calidad (Miembro)",
                            Name_pt = "Qualidade (Membro)"
                        },
                        new
                        {
                            Key = "Quality.User",
                            Name = "Quality User",
                            Name_en = "Quality (User)",
                            Name_es = "Calidad (Usuario)",
                            Name_pt = "Qualidade (Usuário)"
                        },
                        new
                        {
                            Key = "Safety.Admin",
                            Name = "Safety Admin",
                            Name_en = "Safety (Manager)",
                            Name_es = "Seguridad (Gerente)",
                            Name_pt = "Segurança (Gestão)"
                        },
                        new
                        {
                            Key = "Safety.Member",
                            Name = "Safety Member",
                            Name_en = "Safety (Member)",
                            Name_es = "Seguridad (Miembro)",
                            Name_pt = "Segurança (Membro)"
                        },
                        new
                        {
                            Key = "Safety.User",
                            Name = "Safety User",
                            Name_en = "Safety (User)",
                            Name_es = "Seguridad (Usuario)",
                            Name_pt = "Segurança (Usuário)"
                        },
                        new
                        {
                            Key = "Warehouse.Admin",
                            Name = "Warehouse Admin",
                            Name_en = "Warehouse (Manager)",
                            Name_es = "Almacén (Gerente)",
                            Name_pt = "Almoxarifado (Gestão)"
                        },
                        new
                        {
                            Key = "Warehouse.Member",
                            Name = "Warehouse Member",
                            Name_en = "Warehouse (Member)",
                            Name_es = "Almacén (Miembro)",
                            Name_pt = "Almoxarifado (Membro)"
                        },
                        new
                        {
                            Key = "Warehouse.User",
                            Name = "Warehouse User",
                            Name_en = "Warehouse (User)",
                            Name_es = "Almacén (Usuario)",
                            Name_pt = "Almoxarifado (Usuário)"
                        });
                });

            modelBuilder.Entity("Hephaestus.Architect.Models.Version", b =>
                {
                    b.Property<int>("Build")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Build");

                    b.HasIndex("Build")
                        .IsUnique();

                    b.HasIndex("Force");

                    b.ToTable("Versions", (string)null);

                    b.HasData(
                        new
                        {
                            Build = 3,
                            Force = 3,
                            Name = "v2.0.0 (Alpha 3)",
                            Notes = ""
                        });
                });

            modelBuilder.Entity("Hephaestus.Architect.Models.Preferences", b =>
                {
                    b.HasOne("Hephaestus.Architect.Models.Language", "LanguageData")
                        .WithMany()
                        .HasForeignKey("Language");

                    b.HasOne("Hephaestus.Architect.Models.Theme", "ThemeData")
                        .WithMany()
                        .HasForeignKey("Theme");

                    b.HasOne("Hephaestus.Architect.Models.User", "UserData")
                        .WithOne("Preferences")
                        .HasForeignKey("Hephaestus.Architect.Models.Preferences", "User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LanguageData");

                    b.Navigation("ThemeData");

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("Hephaestus.Architect.Models.User", b =>
                {
                    b.HasOne("Hephaestus.Architect.Models.Active", "ActiveData")
                        .WithMany()
                        .HasForeignKey("Active")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hephaestus.Architect.Models.User", "CreatedByData")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Hephaestus.Architect.Models.User", "DeletedByData")
                        .WithMany()
                        .HasForeignKey("DeletedBy");

                    b.HasOne("Hephaestus.Architect.Models.Hidden", "HiddenData")
                        .WithMany()
                        .HasForeignKey("Hidden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hephaestus.Architect.Models.UserRole", "RoleData")
                        .WithMany()
                        .HasForeignKey("Role");

                    b.HasOne("Hephaestus.Architect.Models.User", "UpdatedByData")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("ActiveData");

                    b.Navigation("CreatedByData");

                    b.Navigation("DeletedByData");

                    b.Navigation("HiddenData");

                    b.Navigation("RoleData");

                    b.Navigation("UpdatedByData");
                });

            modelBuilder.Entity("Hephaestus.Architect.Models.User", b =>
                {
                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
